<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCquxW6j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCquxW6j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCquxW6j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCquxW6j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCquxW6j\App_KernelDevDebugContainer([
    'container.build_hash' => 'CquxW6j',
    'container.build_id' => '3c0904ad',
    'container.build_time' => 1586968115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCquxW6j');
