<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKou7qNj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKou7qNj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKou7qNj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKou7qNj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKou7qNj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kou7qNj',
    'container.build_id' => 'e33d9269',
    'container.build_time' => 1586872916,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKou7qNj');
